version: '3.8'

networks:
    tc_bridge:
        external: true

services:
    jenkins:
        restart: always
        image: localhost:5000/jenkins-v1:latest
        networks:
            tc_bridge:
                ipv4_address: 192.168.3.18
        ports:
            - "8080:8080"
            - "50018:50000"
            
        user: root
        container_name: jenkins-v1
      
        volumes:
            - /opt/docker/jenkins/jenkins_home:/var/jenkins_home:rw
            - /opt/docker/jenkins/docker-certs:/certs/client:ro
            - /opt/docker/jenkins/docker.sock:/var/run/docker.sock

volumes:
    jenkins_home:
    docker.sock:
    docker-certs:
